name: PaperDialogDSL
version: '${version}'
main: xyz.axiumyu.paperDialogDsl.PaperDialogDSL
bootstrapper: xyz.axiumyu.paperDialogDsl.PaperDialogDSLBootstrap
loader: xyz.axiumyu.paperDialogDsl.PaperDialogDSLLoader
api-version: '1.21.11'
load: POSTWORLD
