name: PlayerDisplay
version: '${version}'
main: xyz.axiumyu.playerDisplay.PlayerDisplay
bootstrapper: xyz.axiumyu.playerDisplay.PlayerDisplayBootstrap
loader: xyz.axiumyu.playerDisplay.PlayerDisplayLoader
api-version: '1.21.11'
load: POSTWORLD
